# Generated by Django 3.1.2 on 2020-10-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PdfApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='desc',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='upload',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
