# Generated by Django 3.1.2 on 2020-10-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PdfApp', '0005_auto_20201006_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='logo',
            field=models.ImageField(default='emart.png', upload_to='logos'),
        ),
    ]
