# Generated by Django 3.1.2 on 2020-10-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PdfApp', '0007_auto_20201006_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='logo',
            field=models.ImageField(blank=True, default='static/emart.png', upload_to='pics'),
        ),
    ]
