# Generated by Django 3.1.2 on 2020-10-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PdfApp', '0010_auto_20201006_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='logo',
            field=models.ImageField(blank=True, default='logos/emart.png', null=True, upload_to='logos'),
        ),
    ]
