# Generated by Django 3.1.2 on 2020-10-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PdfApp', '0012_remove_blog_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='logo',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
