# Generated by Django 3.1.2 on 2020-10-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PdfApp', '0014_auto_20201006_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='logo',
        ),
    ]
